// On-plan authored drills (NO API calls) — personalized to Adam's real mistake-patterns + deeper levels.
// Merges into items.json + items.js, deduped.
import fs from 'fs';
const DIR='C:/Users/Adam/whetstone';
const SKILLS={bug:'Finding the real bug',problem:'Naming the real problem',clear:'Being clear',thinking:'Thinking it through',ripples:'Seeing the ripples',doubt:'Not taking it on faith',first:'First things first',flip:'Flipping the problem',good:'Knowing what is good'};
// p = personalized (built from Adam's recurring misses: vague asks, no problem stated, unconstrained delegation, assuming, missing ripples)
const B=[
// ---- problem (naming the real problem) ----
{sk:'problem',level:1,p:1,scenario:"Someone tells you 'the app feels slow.' You're about to dig in.",optionA:"Ask which screen feels slow and what they were doing right before — 'slow' can mean ten different things.",optionB:"Start speeding up the heaviest page, since that's probably the cause.",better:'A',why:"Pin down what 'slow' actually points at before you chase anything.",trap:"The heaviest page feels like the obvious culprit."},
{sk:'problem',level:2,p:1,scenario:"You say: 'clean up this messy part, it's been bugging me.'",optionA:"Point at the exact thing that bugs you and say what it should look like when it's done.",optionB:"Just say 'make it cleaner' and trust they'll see what you see.",better:'A',why:"Name the actual thing that's wrong and what 'done' looks like, or they'll guess.",trap:"It feels obvious to you because you can already see it in your head."},
{sk:'problem',level:3,scenario:"Two people report the same screen 'doesn't work.' One on a phone, one on a laptop.",optionA:"Ask each what they expected to happen and what happened instead — they may be hitting different things.",optionB:"Assume it's one bug and start fixing the screen.",better:'A',why:"'Doesn't work' from two people can be two different problems wearing one complaint.",trap:"Same screen, same words — feels like one bug."},
{sk:'problem',level:4,scenario:"A number on a report looks wrong. It's off by a little, not a lot.",optionA:"First ask whether 'wrong' means the math is off or the expectation was off — maybe the number is right and the assumption isn't.",optionB:"Go hunt for the math error in the calculation.",better:'A',why:"Sometimes the real problem is the expectation, not the number.",trap:"A wrong-looking number screams 'math bug'."},
// ---- clear (being clear) ----
{sk:'clear',level:1,p:1,scenario:"You want a button moved.",optionA:"Move the Save button to the bottom-right of the form.",optionB:"Put the button somewhere that makes more sense.",better:'A',why:"Say exactly where — don't make anyone read your mind.",trap:"'Somewhere better' is crystal clear in your head."},
{sk:'clear',level:2,p:1,scenario:"You're handing off a big task you don't feel like spelling out.",optionA:"Here's the one rule that matters: don't touch the login flow. Everything else is your call.",optionB:"You know what's best — just do the whole thing however you want.",better:'A',why:"Hand over freedom, but pin the one constraint that would hurt if missed.",trap:"Full trust feels efficient and generous."},
{sk:'clear',level:2,p:1,scenario:"You ask for 'a few small tweaks to make it feel nicer.'",optionA:"List the three tweaks you mean, even roughly, so 'nicer' has edges.",optionB:"Leave it as 'make it feel nicer' — they'll figure out your taste.",better:'A',why:"Your taste isn't visible to them; give 'nicer' something to aim at.",trap:"You'll know it when you see it — so it feels pointless to spell out."},
{sk:'clear',level:3,scenario:"You write: 'fix the thing we talked about yesterday.'",optionA:"Restate the thing in one line — yesterday's context isn't in front of them now.",optionB:"Send it as-is; you both remember the conversation.",better:'A',why:"Shared memory fades; a one-line restate costs you nothing and saves a wrong guess.",trap:"It's fresh in your mind, so it feels fresh in theirs."},
// ---- first (first things first) ----
{sk:'first',level:1,p:1,scenario:"Five things are broken and you have one hour.",optionA:"Fix the one that stops people from signing up — the rest can wait.",optionB:"Knock them out top to bottom in the order they're listed.",better:'A',why:"Do the one that matters most first, not the first one you happened to see.",trap:"Going in order feels productive and tidy."},
{sk:'first',level:2,p:1,scenario:"You want to add three features and also ship this week.",optionA:"Pick the one feature people actually asked for; park the other two.",optionB:"Try to fit all three in and see how far you get.",better:'A',why:"One finished thing beats three half-things when the clock matters.",trap:"All three feel important because they're all your ideas."},
{sk:'first',level:3,scenario:"A small annoying bug and a quiet risk that could lose data, both on your list.",optionA:"Handle the quiet data risk first, even though the annoying bug is louder.",optionB:"Squash the annoying one first to get it off your plate.",better:'A',why:"Loud and urgent aren't the same as important; protect what you can't undo.",trap:"The annoying bug is in your face; the risk is silent."},
// ---- doubt (not taking it on faith) ----
{sk:'doubt',level:1,scenario:"The assistant says 'done — it works now.'",optionA:"Open it yourself and try the exact thing that was broken.",optionB:"Good — move on to the next task.",better:'A',why:"See it work with your own eyes before you trust 'done.'",trap:"'Done' is exactly what you were hoping to hear."},
{sk:'doubt',level:2,p:1,scenario:"You're told a change is 'totally safe, won't affect anything else.'",optionA:"Ask what it touches and check one place that uses it before believing 'safe.'",optionB:"Take the word 'safe' and ship it.",better:'A',why:"'Safe' is a claim, not a check — spend ten seconds confirming it.",trap:"You want it to be safe, so 'safe' lands easy."},
{sk:'doubt',level:3,scenario:"A test passes and everyone's relieved.",optionA:"Ask whether the test actually covers the case that broke last time.",optionB:"Green means good — call it.",better:'A',why:"A passing test only proves what it checks; make sure it checks the real worry.",trap:"Green feels like permission to stop looking."},
// ---- ripples (seeing the ripples) ----
{sk:'ripples',level:2,scenario:"You rename a setting from 'Sound' to 'Audio.'",optionA:"First find everywhere that word shows up — old saved settings might still say 'Sound.'",optionB:"Change the label; it's just one word.",better:'A',why:"A rename can quietly break the places still expecting the old word.",trap:"One word — it looks completely harmless."},
{sk:'ripples',level:3,scenario:"You make sign-in faster by remembering people longer.",optionA:"Think about the shared computer case before shipping — longer memory means the next person might land in someone's account.",optionB:"Ship it; faster sign-in is just better.",better:'A',why:"A win in one place can open a hole in another — follow the ripple.",trap:"Faster and smoother feels purely good."},
{sk:'ripples',level:4,scenario:"You let users pick any username they want, finally.",optionA:"Consider names that look like system words or like other people's names before opening it up.",optionB:"Freedom's good — let them type anything.",better:'A',why:"Total freedom in one field can collide with everything that reads that field.",trap:"Giving users freedom feels generous and simple."},
// ---- bug (finding the real bug) ----
{sk:'bug',level:2,scenario:"A page breaks, but only some of the time.",optionA:"Write down exactly what you did the times it broke, and look for what those times share.",optionB:"Reload and tweak things until it stops happening.",better:'A',why:"Hunt for what the broken moments have in common instead of poking at random.",trap:"Random poking sometimes makes it go away — for a while."},
{sk:'bug',level:3,scenario:"Something broke today and you changed three things yesterday.",optionA:"Undo the three changes one at a time to see which one did it.",optionB:"Guess which change was the culprit and fix that.",better:'A',why:"Change one thing at a time so the cause can't hide among the others.",trap:"You've got a strong hunch which one it was."},
// ---- thinking (thinking it through) ----
{sk:'thinking',level:2,scenario:"You're sure the fix is X.",optionA:"Say out loud why X fixes it — if you can't, you don't actually know yet.",optionB:"Just do X; you've got a good feeling about it.",better:'A',why:"Make yourself spell out the steps; a feeling isn't a reason.",trap:"The good feeling is right often enough to be dangerous."},
{sk:'thinking',level:3,scenario:"An idea sounds great in your head and you want to build it now.",optionA:"Walk one real person through it start to finish, out loud, before building.",optionB:"Start building; you'll find the holes as you go.",better:'A',why:"Talking it through end-to-end finds the holes cheaper than building does.",trap:"Building feels like progress; talking feels like delay."},
// ---- good (knowing what is good) ----
{sk:'good',level:2,scenario:"Two designs: one flashy, one plain but instantly obvious to use.",optionA:"Pick the plain one if a stranger could use it without thinking.",optionB:"Pick the flashy one — it's more impressive.",better:'A',why:"Real quality is whether it works without thought, not whether it dazzles.",trap:"Flashy reads as 'high quality' at a glance."},
{sk:'good',level:3,scenario:"Something you made works, but a small part of it still nags at you.",optionA:"Trust the nag — find what's bugging you and name it before calling it done.",optionB:"It works, so call it done; the nagging feeling is just nerves.",better:'A',why:"A trained nag is usually pointing at a real flaw you haven't worded yet.",trap:"'It works' is a tempting place to stop."},
// ---- flip (flipping the problem) ----
{sk:'flip',level:2,scenario:"You're stuck cramming tabs onto a small phone screen.",optionA:"Ask whether it even needs tabs — maybe it's just one thing you scroll.",optionB:"Keep shrinking the tabs until they all fit.",better:'A',why:"Step back and question the shape of the problem, not just its size.",trap:"Shrinking is the obvious next move when something won't fit."},
{sk:'flip',level:3,scenario:"People keep misusing a feature in a way you didn't intend.",optionA:"Ask whether the way they're using it is actually the better feature.",optionB:"Add rules to stop them from using it the wrong way.",better:'A',why:"Sometimes the 'wrong' use is the product telling you what it wants to be.",trap:"Misuse feels like a problem to lock down, not a hint to follow."},
];
let items=JSON.parse(fs.readFileSync(`${DIR}/items.json`,'utf8'));
items.forEach(it=>{it.level=it.level||it.difficulty||1;it.skill=SKILLS[it.sk]||it.skill;});
const norm=s=>s.toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim().slice(0,90);
const have=new Set(items.map(it=>norm(it.scenario)));
let next=items.reduce((m,it)=>Math.max(m,+(String(it.id).replace(/\D/g,''))||0),0);
let added=0;
for(const b of B){ if(have.has(norm(b.scenario)))continue; b.skill=SKILLS[b.sk]; b.id='w'+(++next); if(b.p){b.personalized=true;delete b.p;} items.push(b); have.add(norm(b.scenario)); added++; }
fs.writeFileSync(`${DIR}/items.json`,JSON.stringify(items,null,1));
fs.writeFileSync(`${DIR}/items.js`,'window.ITEMS = '+JSON.stringify(items)+';');
const byLv={}; for(const it of items){byLv[it.sk]=(byLv[it.sk]||{}); byLv[it.sk][it.level]=(byLv[it.sk][it.level]||0)+1;}
console.log(`added ${added} authored drills | total ${items.length} | personalized ${items.filter(i=>i.personalized).length}`);
console.log('per-skill levels:',JSON.stringify(byLv));
